// Generated by gen-glyph-names.mjs — do not edit.
export const NAME_PAGES = new Set<number>([0, 1, 2, 3, 4, 5, 6, 9, 20, 21, 26, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 44, 45, 49, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 95, 448])
