#!/usr/bin/env node
/* gen-index -- COMPONENTS.md and HOST-CONTRACT.md, generated, never hand-kept.
 *
 * A hand-kept list is the SLIDERS.md census again, right up until it is not. So the
 * component index is read off index.ts (each export block and the comment above it),
 * and the host contract off .tokenlint.json (hostTokens + hostTokenDocs). Which app draws
 * what is scanned from the consumers' own sources when they are present: siblings on a
 * laptop, hosts/ in CI (WM_CONSUMERS overrides, as name=dir pairs).
 *
 * consumers.yml fails a push that changed either input without regenerating. */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, resolve, extname } from 'node:path'

const ROOT = resolve(new URL('..', import.meta.url).pathname)
const idx = readFileSync(process.env.WM_INDEX ?? join(ROOT, 'index.ts'), 'utf8')
const cfg = JSON.parse(readFileSync(join(ROOT, '.tokenlint.json'), 'utf8'))

/* ---- consumers: name -> concatenated source text (their own files, not shared/) ---- */
const DEFAULT = {
  'font-proofer': '../font-proofer/src',
  'ReCal': '../ReCal/src',
  'opsz-proofer': '../wordmarktools/opsz-proofer',
  'Kernpare': '../wordmarktools/kernpare/index.html',
}
const spec = process.env.WM_CONSUMERS
  ? Object.fromEntries(process.env.WM_CONSUMERS.split(',').map(p => p.split('=')))
  : DEFAULT
const EXT = new Set(['.ts', '.tsx', '.js', '.jsx', '.html', '.py'])
function walk(p, out = []) {
  if (!existsSync(p)) return out
  const st = statSync(p)
  if (st.isFile()) { if (EXT.has(extname(p))) out.push(p); return out }
  for (const f of readdirSync(p)) {
    if (f === 'node_modules' || f === 'shared' || f === 'dist' || f.startsWith('.')) continue
    walk(join(p, f), out)
  }
  return out
}
const consumers = {}
for (const [name, dir] of Object.entries(spec)) {
  const files = walk(resolve(ROOT, dir))
  if (files.length) consumers[name] = files.map(f => readFileSync(f, 'utf8')).join('\n')
}
const usedBy = name => Object.entries(consumers).filter(([, t]) => new RegExp(`\\b${name}\\b`).test(t)).map(([n]) => n)

/* ---- index.ts -> blocks: {comment, exports[], from} ---- */
const blocks = []
let comment = []
for (const raw of idx.split('\n')) {
  const line = raw.trim()
  if (line.startsWith('//')) { comment.push(line.replace(/^\/\/\s?/, '')); continue }
  const m = /^export (type )?\{([^}]*)\} from '([^']+)'/.exec(line)
  if (m) {
    const names = m[2].split(',').map(s => s.trim().split(/\s+as\s+/).pop()).filter(Boolean)
    const from = m[3].replace('./src/', '')
    let b = blocks.find(b => b.from === from)
    if (!b) { b = { comment: comment.join(' ').trim(), from, values: [], types: [] }; blocks.push(b) }
    else if (!b.comment && comment.length) b.comment = comment.join(' ').trim()
    ;(m[1] ? b.types : b.values).push(...names)
    comment = []
    continue
  }
  // multi-line `export type {` blocks and blank lines: keep the comment for the next export
  if (line === '' && comment.length && blocks.length && !blocks[blocks.length - 1].comment) blocks[blocks.length - 1].comment = comment.join(' ').trim()
  if (line === '') comment = []
}
// CSS-only modules the barrel describes but cannot export
const cssOnly = [...idx.matchAll(/\((src\/[a-z.-]+\.css) -- no JS to export[^)]*\)/g)].map(m => m[1])

const specFor = from => {
  const f = from.replace(/\.(tsx?|js)$/, '')
  const map = { AxisSlider: 'DIAL.md + GESTURES.md', AxisTriplet: 'GESTURES.md §9', Icon: 'GESTURES.md §10', ThemeSwitch: 'GESTURES.md §8', 'theme.js': 'GESTURES.md §8', Chevron: 'SLIDERS.md (icon census)', type: 'TYPOGRAPHY.md', gradient: 'GRADIENTS.md', Fitting: 'FITTING-MAP.md', flattersatz: 'FITTING-MAP.md', letterbox: 'README (letterbox)', StopSlider: 'DIAL.md §7' }
  return map[f] ?? map[from] ?? '—'
}
let md = `# Components\n\nGenerated by \`scripts/gen-index.mjs\` from \`index.ts\` and the consumers' own sources.\nDo not edit; CI fails a stale copy. The "drawn by" column is read from each consumer's \`main\`, so regenerate from CI's output (the browser job prints the diff), not from a laptop on a branch. Consumers scanned: ${Object.keys(consumers).join(', ') || 'none found'}.\n\n| export | what | drawn by | spec |\n| --- | --- | --- | --- |\n`
for (const b of blocks) {
  const all = [...b.values]
  const names = all.map(n => '`' + n + '`').join(' ')
  const by = [...new Set(all.flatMap(usedBy))]
  const what = (b.comment || '').replace(/\|/g, '\\|').slice(0, 220) + ((b.comment || '').length > 220 ? '…' : '')
  md += `| ${names || '*(types only)*'} | ${what || '—'} | ${by.join(', ') || '—'} | ${specFor(b.from)} |\n`
}
if (cssOnly.length) md += `\nCSS-only modules (imported from an app's entry stylesheet, nothing to export): ${cssOnly.map(c => '`' + c + '`').join(', ')}.\n`
/* ---- the marks: which Material Symbols name each consumer draws ---- */
const marks = {}
for (const [name, text] of Object.entries(consumers)) {
  const found = new Set([...text.matchAll(/<Icon\s+name=["']([a-z_0-9]+)/g)].map(m => m[1]))
  for (const m of text.matchAll(/material-symbols-outlined["'][^>]*>\s*([a-z_0-9]+)\s*</g)) found.add(m[1])
  for (const m of text.matchAll(/(brightness_auto|light_mode|dark_mode)/g)) found.add(m[1])   // ThemeSwitch's three
  for (const n of found) (marks[n] ??= new Set()).add(name)
}
const ownMarks = new Set([...idx.matchAll(/'([a-z_0-9]+)'/g)].map(m => m[1]).filter(() => false))
if (Object.keys(marks).length) {
  md += `\n## Marks\n\nMaterial Symbols names each consumer draws (\`<Icon name>\` and raw ligatures), so removing one is a search, not a guess. The subset font carries what \`scripts/\` last cut; a name here that is not in it prints as text.\n\n| mark | drawn by |\n| --- | --- |\n`
  for (const [n, who] of Object.entries(marks).sort()) md += `| \`${n}\` | ${[...who].join(', ')} |\n`
}
writeFileSync(join(ROOT, 'COMPONENTS.md'), md)

/* ---- host contract ---- */
let hc = `# The host contract\n\nGenerated by \`scripts/gen-index.mjs\` from \`.tokenlint.json\` (\`hostTokens\` + \`hostTokenDocs\`).\nDo not edit here; edit the JSON. \`lint:tokens\` fails a host token with no entry.\n\nEvery token below is the consuming app's to define on its root. \`color.css\`, \`type.css\`, \`space.css\` and \`motion.css\` give defaults for the ramp, the roles, the scale and the durations; the rest fall back as the last column says. The two that have no safe fallback are marked.\n\n| token | what it is | without it |\n| --- | --- | --- |\n`
for (const t of cfg.hostTokens) {
  const [what, without] = cfg.hostTokenDocs[t]
  const hard = /VANISHES|black on black/.test(without) ? ' **⚠**' : ''
  hc += `| \`${t}\`${hard} | ${what} | ${without} |\n`
}
hc += `\nRuntime tokens (\`${cfg.runtimeTokens.join('`, `')}\`) are set by this package's own JS on its own elements and are not a contract with anybody.\n`
writeFileSync(join(ROOT, 'HOST-CONTRACT.md'), hc)
console.log(`COMPONENTS.md: ${blocks.length} export groups · HOST-CONTRACT.md: ${cfg.hostTokens.length} tokens · consumers: ${Object.keys(consumers).join(', ') || 'none'}`)
